import type { Charity, Donation, UserProfile, Streak, Badge, FeedItem } from '@/types';

export const CHARITIES: Charity[] = [
  {
    id: 'feeding-america',
    displayName: 'Feeding America',
    legalName: 'Feeding America',
    category: 'hunger',
    emoji: '🥗',
    missionSummary: 'Fighting hunger in communities across the United States through a network of food banks.',
    impactSummary: '$10 feeds a family for a day',
    website: 'https://www.feedingamerica.org',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 98,
    urgencyScore: 90,
    impactMetricLabel: 'meals per dollar',
    impactPerDollar: 10,
  },
  {
    id: 'wwf',
    displayName: 'World Wildlife Fund',
    legalName: 'World Wildlife Fund, Inc.',
    category: 'animals',
    emoji: '🐼',
    missionSummary: 'Protecting wildlife and wild places for future generations through science and conservation.',
    impactSummary: '$5 protects 1 acre of habitat',
    website: 'https://www.worldwildlife.org',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 95,
    urgencyScore: 85,
    impactMetricLabel: 'acres protected per $5',
    impactPerDollar: 0.2,
  },
  {
    id: 'st-jude',
    displayName: "St. Jude Children's Hospital",
    legalName: "St. Jude Children's Research Hospital",
    category: 'children',
    emoji: '🏥',
    missionSummary: "Advancing cures and preventing pediatric catastrophic diseases through research and treatment.",
    impactSummary: '$25 funds 1 hour of research',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 97,
    urgencyScore: 88,
    impactMetricLabel: 'research hours per $25',
    impactPerDollar: 0.04,
  },
  {
    id: 'nature-conservancy',
    displayName: 'The Nature Conservancy',
    legalName: 'The Nature Conservancy',
    category: 'environment',
    emoji: '🌿',
    missionSummary: 'Protecting the lands and waters on which all life depends through science and partnerships.',
    impactSummary: '$5 plants 3 trees',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 93,
    urgencyScore: 82,
    impactMetricLabel: 'trees planted per $5',
    impactPerDollar: 0.6,
  },
  {
    id: 'khan-academy',
    displayName: 'Khan Academy',
    legalName: 'Khan Academy',
    category: 'education',
    emoji: '📚',
    missionSummary: 'Providing a free, world-class education for anyone, anywhere.',
    impactSummary: '$10 gives a student 1 month of learning',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 91,
    urgencyScore: 75,
    impactMetricLabel: 'months of learning per $10',
    impactPerDollar: 0.1,
  },
  {
    id: 'doctors-without-borders',
    displayName: 'Doctors Without Borders',
    legalName: 'Médecins Sans Frontières USA',
    category: 'health',
    emoji: '🩺',
    missionSummary: 'Delivering emergency medical care to people affected by conflict, epidemics, and disasters.',
    impactSummary: '$20 covers 1 medical consultation',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 96,
    urgencyScore: 95,
    impactMetricLabel: 'consultations per $20',
    impactPerDollar: 0.05,
  },
  {
    id: 'team-rubicon',
    displayName: 'Team Rubicon',
    legalName: 'Team Rubicon USA',
    category: 'disaster_relief',
    emoji: '🚑',
    missionSummary: 'Uniting military veterans with first responders to rapidly deploy disaster relief.',
    impactSummary: '$15 deploys 1 veteran responder',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 87,
    urgencyScore: 92,
    impactMetricLabel: 'responders deployed per $15',
    impactPerDollar: 0.067,
  },
  {
    id: 'habitat-humanity',
    displayName: 'Habitat for Humanity',
    legalName: 'Habitat for Humanity International',
    category: 'housing',
    emoji: '🏠',
    missionSummary: 'Building affordable homes and empowering families to build better lives.',
    impactSummary: '$30 buys materials for 1 hour of building',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 92,
    urgencyScore: 80,
    impactMetricLabel: 'build hours per $30',
    impactPerDollar: 0.033,
  },
  {
    id: 'vfw-foundation',
    displayName: 'VFW Foundation',
    legalName: 'Veterans of Foreign Wars Foundation',
    category: 'veterans',
    emoji: '🎖️',
    missionSummary: 'Supporting veterans and their families through programs, scholarships, and advocacy.',
    impactSummary: '$25 supports 1 veteran family',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 85,
    urgencyScore: 78,
    impactMetricLabel: 'families supported per $25',
    impactPerDollar: 0.04,
  },
  {
    id: 'aspca',
    displayName: 'ASPCA',
    legalName: 'American Society for the Prevention of Cruelty to Animals',
    category: 'animals',
    emoji: '🐾',
    missionSummary: 'Providing effective means for the prevention of cruelty to animals throughout the United States.',
    impactSummary: '$15 saves 1 animal',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 90,
    urgencyScore: 83,
    impactMetricLabel: 'animals saved per $15',
    impactPerDollar: 0.067,
  },
  {
    id: 'red-cross',
    displayName: 'American Red Cross',
    legalName: 'American National Red Cross',
    category: 'disaster_relief',
    emoji: '❤️',
    missionSummary: 'Preventing and alleviating human suffering in the face of emergencies.',
    impactSummary: '$10 provides emergency shelter for 1 night',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 96,
    urgencyScore: 90,
    impactMetricLabel: 'shelter nights per $10',
    impactPerDollar: 0.1,
  },
  {
    id: 'local-food-bank',
    displayName: 'Austin Food Bank',
    legalName: 'Central Texas Food Bank',
    category: 'hunger',
    emoji: '🍎',
    missionSummary: 'Nourishing hungry people and leading the community in the fight against hunger in Central Texas.',
    impactSummary: '$5 provides 15 meals',
    verificationStatus: 'VERIFIED',
    cityRegion: 'Austin, TX',
    country: 'US',
    popularityScore: 78,
    urgencyScore: 88,
    impactMetricLabel: 'meals per $5',
    impactPerDollar: 3,
  },
  {
    id: 'humane-society',
    displayName: 'Humane Society',
    legalName: 'Humane Society of the United States',
    category: 'animals',
    emoji: '🐶',
    missionSummary: 'Fighting animal cruelty in all its forms and celebrating the human-animal bond.',
    impactSummary: '$20 funds 1 day of animal care',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 88,
    urgencyScore: 80,
    impactMetricLabel: 'care days per $20',
    impactPerDollar: 0.05,
  },
  {
    id: 'pencils-promise',
    displayName: "Pencils of Promise",
    legalName: 'Pencils of Promise',
    category: 'education',
    emoji: '✏️',
    missionSummary: 'Building schools and increasing educational opportunities in developing nations.',
    impactSummary: '$25 funds 1 day of school',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 82,
    urgencyScore: 85,
    impactMetricLabel: 'school days funded per $25',
    impactPerDollar: 0.04,
  },
  {
    id: 'sierra-club',
    displayName: 'Sierra Club Foundation',
    legalName: 'Sierra Club Foundation',
    category: 'environment',
    emoji: '🏔️',
    missionSummary: 'Protecting and restoring the natural environment through advocacy and education.',
    impactSummary: '$10 protects 5 acres of wilderness',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 83,
    urgencyScore: 79,
    impactMetricLabel: 'acres protected per $10',
    impactPerDollar: 0.5,
  },
  {
    id: 'unicef',
    displayName: 'UNICEF USA',
    legalName: 'United States Fund for UNICEF',
    category: 'children',
    emoji: '👶',
    missionSummary: "Working to protect children's rights and provide humanitarian aid to children worldwide.",
    impactSummary: '$10 provides vaccines for 5 children',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 94,
    urgencyScore: 91,
    impactMetricLabel: 'vaccines per $10',
    impactPerDollar: 0.5,
  },
  {
    id: 'charity-water',
    displayName: 'charity: water',
    legalName: 'charity: water',
    category: 'health',
    emoji: '💧',
    missionSummary: 'Bringing clean and safe drinking water to people in developing countries.',
    impactSummary: '$30 gives 1 person clean water for life',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 92,
    urgencyScore: 87,
    impactMetricLabel: 'people with clean water per $30',
    impactPerDollar: 0.033,
  },
  {
    id: 'direct-relief',
    displayName: 'Direct Relief',
    legalName: 'Direct Relief',
    category: 'health',
    emoji: '💊',
    missionSummary: 'Improving the health and lives of people affected by poverty or disaster.',
    impactSummary: '$25 delivers essential medicines',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 89,
    urgencyScore: 88,
    impactMetricLabel: 'medicine packages per $25',
    impactPerDollar: 0.04,
  },
  {
    id: 'wounded-warrior',
    displayName: 'Wounded Warrior Project',
    legalName: 'Wounded Warrior Project, Inc.',
    category: 'veterans',
    emoji: '🦅',
    missionSummary: 'Honoring and empowering wounded warriors through programs and services.',
    impactSummary: '$20 funds 1 hour of mental health support',
    verificationStatus: 'VERIFIED',
    country: 'US',
    popularityScore: 91,
    urgencyScore: 86,
    impactMetricLabel: 'support hours per $20',
    impactPerDollar: 0.05,
  },
  {
    id: 'local-shelter',
    displayName: 'Austin Shelter for Women',
    legalName: 'SafePlace Austin',
    category: 'housing',
    emoji: '🏡',
    missionSummary: 'Ending sexual and domestic violence in our community through safety, healing, and prevention.',
    impactSummary: '$40 provides 1 night of safe shelter',
    verificationStatus: 'VERIFIED',
    cityRegion: 'Austin, TX',
    country: 'US',
    popularityScore: 74,
    urgencyScore: 93,
    impactMetricLabel: 'shelter nights per $40',
    impactPerDollar: 0.025,
  },
];

export const DEMO_USER: UserProfile = {
  id: 'demo-user-id',
  name: 'Alex Rivera',
  email: 'alex@email.com',
  privacyMode: 'PUBLIC',
  cityRegion: 'Austin, TX',
  bio: 'Passionate about ending hunger and protecting our planet. 🌍 Every dollar counts.',
  username: 'alexgives',
  memberSince: '2024-01-15',
};

// Helper to build sample donations
function makeDonation(
  id: string,
  charityId: string,
  amountCents: number,
  donatedAt: string,
  fundingSource: string = 'card'
): Donation {
  const feeCents = 0;
  const tipCents = 0;
  return {
    id,
    userId: 'demo-user-id',
    charityId,
    amountCents,
    tipCents,
    feeCents,
    totalCents: amountCents,
    charityReceivesCents: amountCents,
    currency: 'usd',
    status: 'SUCCEEDED',
    privacyMode: 'PUBLIC',
    fundingSource,
    stripePaymentIntentId: `pi_mock_${id}`,
    idempotencyKey: `idem_${id}`,
    donatedAt,
    createdAt: donatedAt,
  };
}

export const SAMPLE_DONATIONS: Donation[] = [
  makeDonation('d1', 'feeding-america', 1000, '2024-01-08', 'quick-give'),
  makeDonation('d2', 'wwf', 500, '2024-01-14', 'apple-pay'),
  makeDonation('d3', 'khan-academy', 1000, '2024-01-22', 'card'),
  makeDonation('d4', 'feeding-america', 500, '2024-02-03', 'quick-give'),
  makeDonation('d5', 'nature-conservancy', 2500, '2024-02-14', 'card'),
  makeDonation('d6', 'st-jude', 1000, '2024-02-19', 'apple-pay'),
  makeDonation('d7', 'doctors-without-borders', 2000, '2024-03-05', 'card'),
  makeDonation('d8', 'feeding-america', 100, '2024-03-10', 'quick-give'),
  makeDonation('d9', 'charity-water', 3000, '2024-03-22', 'card'),
  makeDonation('d10', 'aspca', 1500, '2024-04-01', 'apple-pay'),
  makeDonation('d11', 'habitat-humanity', 2500, '2024-04-15', 'card'),
  makeDonation('d12', 'unicef', 1000, '2024-04-28', 'quick-give'),
  makeDonation('d13', 'red-cross', 5000, '2024-05-02', 'card'),
  makeDonation('d14', 'feeding-america', 100, '2024-05-10', 'quick-give'),
  makeDonation('d15', 'wwf', 1000, '2024-05-20', 'apple-pay'),
  makeDonation('d16', 'team-rubicon', 1500, '2024-06-05', 'card'),
  makeDonation('d17', 'vfw-foundation', 2500, '2024-06-18', 'apple-pay'),
  makeDonation('d18', 'direct-relief', 1000, '2024-07-04', 'quick-give'),
  makeDonation('d19', 'local-food-bank', 500, '2024-07-15', 'card'),
  makeDonation('d20', 'khan-academy', 2000, '2024-07-28', 'apple-pay'),
  makeDonation('d21', 'nature-conservancy', 1000, '2024-08-08', 'quick-give'),
  makeDonation('d22', 'feeding-america', 2500, '2024-08-20', 'card'),
  makeDonation('d23', 'st-jude', 5000, '2024-09-01', 'apple-pay'),
  makeDonation('d24', 'charity-water', 1000, '2024-09-12', 'quick-give'),
  makeDonation('d25', 'doctors-without-borders', 1500, '2024-09-25', 'card'),
  makeDonation('d26', 'aspca', 100, '2024-10-05', 'quick-give'),
  makeDonation('d27', 'local-shelter', 2500, '2024-10-14', 'apple-pay'),
  makeDonation('d28', 'unicef', 1000, '2024-10-22', 'card'),
  makeDonation('d29', 'feeding-america', 100, '2024-10-31', 'quick-give'),
  makeDonation('d30', 'red-cross', 1000, '2024-11-03', 'card'),
  makeDonation('d31', 'habitat-humanity', 1500, '2024-11-11', 'apple-pay'),
  makeDonation('d32', 'wwf', 500, '2024-11-22', 'quick-give'),
  makeDonation('d33', 'vfw-foundation', 2500, '2024-11-28', 'card'),
  makeDonation('d34', 'feeding-america', 100, '2024-12-01', 'quick-give'),
];

export const SAMPLE_STREAK = {
  userId: 'demo-user-id',
  currentStreak: 7,
  longestStreak: 23,
  lastDonationDate: new Date(Date.now() - 24 * 60 * 60 * 1000), // yesterday
  updatedAt: new Date(),
};

export const SAMPLE_BADGES: Badge[] = [
  { userId: 'demo-user-id', badgeType: 'FIRST_DONATION', awardedAt: '2024-01-08' },
  { userId: 'demo-user-id', badgeType: 'STREAK_7', awardedAt: '2024-01-15' },
  { userId: 'demo-user-id', badgeType: 'CAUSES_5', awardedAt: '2024-04-15' },
  { userId: 'demo-user-id', badgeType: 'EARLY_ADOPTER', awardedAt: '2024-01-15' },
];

const feedUsers = [
  { name: 'Jordan Kim', city: 'Seattle, WA' },
  { name: 'Maya Chen', city: 'Chicago, IL' },
  { name: 'Sam Torres', city: 'Denver, CO' },
  { name: 'Riley Patel', city: 'New York, NY' },
  { name: 'Casey Brown', city: 'Miami, FL' },
  { name: 'Morgan Lee', city: 'Portland, OR' },
  { name: 'Taylor Swift', city: 'Nashville, TN' },
  { name: 'Drew Martinez', city: 'Austin, TX' },
];

export const SAMPLE_FEED: FeedItem[] = CHARITIES.slice(0, 8).map((charity, i) => ({
  id: `feed-${i}`,
  userId: `user-${i}`,
  donationId: `don-feed-${i}`,
  charityId: charity.id,
  charity,
  displayName: feedUsers[i % feedUsers.length].name,
  cityRegion: feedUsers[i % feedUsers.length].city,
  amountCents: [100, 500, 1000, 2500, 5000][i % 5],
  privacyMode: 'PUBLIC',
  createdAt: new Date(Date.now() - i * 3600000 * 2).toISOString(),
  liked: false,
}));
